;/*FB_PKG_DELIM*/

__d("baseTextWithEntitiesApplyRenderers",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.Fragment;function c(e,t,n,r,o,a,i,l,c){var d=e.__typename,m=Object.prototype.hasOwnProperty.call(l,d)?l[d].concat(c):c;return s.jsx(u,{children:m&&m.length>0?m.reduce(function(r,a){return a(r,e,n,o,t)},a):r},i)}c.displayName=c.name+" [from "+i.id+"]",l.default=c}),98);
__d("baseTextWithEntitiesApplyTextTransforms",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){return t!=null?t.reduce(function(e,t){return t(e)},e):e}e.displayName=e.name+" [from "+a.id+"]",i.default=e}),66);
__d("baseTextWithEntitiesProcessRange",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=e||(e=o("react")),c=u.Fragment;function d(e,t,n,a,i,l,d,m,p,_,f,g){var h=(s||(s=o("UnicodeUtils"))).substr(e,t,n-t),y=p.length;h.length>0&&m.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")(h,_)},"c"+t+"_"+y+"_"+g));var C=p.pop();return p[p.length-1].subElements.push(r("baseTextWithEntitiesApplyRenderers")(a,i,l,m,h,m,t+"_"+y+"_"+g,d,f)),C}l.default=d}),98);
__d("baseTextWithEntitiesSortRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e){return Array.from(e).sort(function(e,t){return e.offset-t.offset||t.length-e.length})}i.default=e}),66);
__d("BaseCometTextWithEntitiesBase.react",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","baseTextWithEntitiesProcessRange","baseTextWithEntitiesSortRanges","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=e||(e=o("react")),c=u.Fragment;function d(e){for(var t,n=e.ranges,a=n===void 0?[]:n,i=e.renderers,l=e.transforms,d=l===void 0?[]:l,m=e.text,p=e.disableRangeSort,_=p===void 0?!1:p,f=i!=null?i:{},g=0,h=(t=Object.prototype.hasOwnProperty.call(f,"*")?f["*"]:[])!=null?t:[],y=_?a:r("baseTextWithEntitiesSortRanges")(a),C=[{entity:{__typename:""},entity_is_weak_reference:!1,entityType:"",length:m.length,offset:0,subElements:[]}],b=0;b<y.length;++b){var v=y[b],S=v.entity,R=v.entity_is_weak_reference,L=v.entity_type,E=v.length,k=v.offset;if(g>=m.length||k>m.length)break;for(var I=C[C.length-1],T=I.entity,D=I.entity_is_weak_reference,x=I.entityType,$=I.length,P=I.offset,N=I.subElements,M=P+$;M<=k&&C.length>1;){r("baseTextWithEntitiesProcessRange")(m,g,M,T,D,x,f,N,C,d,h,b),g=M;var w=C[C.length-1];T=w.entity,D=w.entity_is_weak_reference,x=w.entityType,$=w.length,P=w.offset,N=w.subElements,M=P+$}if(g<k&&(C[C.length-1].subElements.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")((s||(s=o("UnicodeUtils"))).substr(m,g,k-g),d)},"c"+g+"_"+C.length)),g=k),P<=k&&M>=k+E)C.push({entity:S,entity_is_weak_reference:R!=null?R:null,entityType:L!=null?L:null,length:E,offset:k,subElements:[]});else{var A=(s||(s=o("UnicodeUtils"))).substr(m,k,E),F=r("baseTextWithEntitiesApplyTextTransforms")(A,d);C[C.length-1].subElements.push(r("baseTextWithEntitiesApplyRenderers")(S,R!=null?R:null,L!=null?L:null,A,A,F,g+"_"+C.length,f,h)),g=k+E}}for(;C.length>1;){var O=C[C.length-1],B=O.entity,W=O.entity_is_weak_reference,q=O.entityType,U=O.length,V=O.offset,H=O.subElements,G=V+U;r("baseTextWithEntitiesProcessRange")(m,g,G,B,W,q,f,H,C,d,h,C.length),g=G}if(g<m.length){var z=C[C.length-1].subElements;z.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")((s||(s=o("UnicodeUtils"))).substr(m,g),d)},"c"+g))}return u.jsx(u.Fragment,{children:C[C.length-1].subElements})}d.displayName=d.name+" [from "+i.id+"]",l.default=d}),98);
__d("baseTextWithEntitiesAdjustRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e,t,n){return e.map(function(e){return babelHelpers.extends({},e,{offset:e.offset-t})}).filter(function(e){return e.offset>=0&&e.offset<n})}i.default=e}),66);
__d("baseTextWithEntitiesFilterRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e){for(var t=[],n=0;n<e.length;n++){var r=e[n];if(r!=null&&r.offset!=null&&r.length!=null&&r.entity!=null&&r.entity.__typename!=null){var o;t.push({entity:r.entity,entity_is_weak_reference:(o=r.entity_is_weak_reference)!=null?o:null,length:r.length,offset:r.offset})}}return t}i.default=e}),66);
__d("baseTextWithEntitiesSplitRangesAndTextIntoParagraphs",["UnicodeUtils","baseTextWithEntitiesAdjustRanges"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t){var n=t.ranges,a=t.text,i=0;return a.split("\n").map(function(t){var a=r("baseTextWithEntitiesAdjustRanges")(n,i,(e||(e=o("UnicodeUtils"))).strlen(t));return i+=e.strlen(t)+1,{ranges:a,text:t}}).filter(function(e){return e.text.trim()!==""})}function u(t,n){var a=t.ranges,i=t.text,l=0;return i.split(/(?=\n\s*\n)/).map(function(t){var i,u,c,d=(i=t.match(/(^\n\s*\n)?([^]*$)/))!=null?i:[],m=(u=d[1])!=null?u:"",p=(c=d[2])!=null?c:t,_=r("baseTextWithEntitiesAdjustRanges")(a,l+m.length,(e||(e=o("UnicodeUtils"))).strlen(p));return l+=e.strlen(t),n?s({ranges:_,text:p}):{ranges:_,text:p}})}l.default=u}),98);
__d("getTextDirectionAttribute",["cr:1080422"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t="auto";return n("cr:1080422")!=null&&window!=null&&(t=n("cr:1080422").isDirectionRTL(e)?"rtl":"ltr"),t}l.default=e}),98);