;/*FB_PKG_DELIM*/

__d("PolarisFollowListContentWrapperQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26750505977951904"}),null);
__d("PolarisFollowListContentWrapperQuery$Parameters",["PolarisFollowListContentWrapperQuery_instagramRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PolarisFollowListContentWrapperQuery_instagramRelayOperation"),metadata:{is_fully_www_executable:!0},name:"PolarisFollowListContentWrapperQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PolarisProfileFollowRoot.entrypoint",["JSResourceForInteraction","PolarisFollowListContentWrapperQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.routeProps.id;return{queries:{userQuery:{parameters:r("PolarisFollowListContentWrapperQuery$Parameters"),variables:{id:e}}}}},root:r("JSResourceForInteraction")("PolarisProfileFollowRoot.react").__setRef("PolarisProfileFollowRoot.entrypoint")};l.default=e}),98);
__d("PolarisProfileRepostsTabContentQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26711518918501861"}),null);
__d("PolarisProfileRepostsTabContentQuery$Parameters",["PolarisProfileRepostsTabContentQuery_instagramRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PolarisProfileRepostsTabContentQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["fetch__XDTUserDict"]},name:"PolarisProfileRepostsTabContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PolarisProfileRepostsTabRoot.entrypoint",["JSResourceForInteraction","PolarisProfileRepostsTabContentQuery$Parameters","buildPolarisProfileRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildPolarisProfileRoute.entrypoint")(r("JSResourceForInteraction")("PolarisProfileRepostsTabRoot.react").__setRef("PolarisProfileRepostsTabRoot.entrypoint"),function(e){var t=e.routeProps;return{queries:{contentQuery:{environmentProviderOptions:{preloaderGroup:"ig_web_profile_feed"},options:{},parameters:r("PolarisProfileRepostsTabContentQuery$Parameters"),variables:{user_id:t.id}}}}});l.default=e}),98);
__d("PolarisProfileTaggedTabContentQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27485417761042436"}),null);
__d("PolarisProfileTaggedTabContentQuery$Parameters",["PolarisProfileTaggedTabContentQuery_instagramRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PolarisProfileTaggedTabContentQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_api__v1__usertags__user_id__feed_connection"]},name:"PolarisProfileTaggedTabContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PolarisProfileTaggedTabRoot.entrypoint",["JSResourceForInteraction","PolarisProfileTaggedTabContentQuery$Parameters","buildPolarisProfileRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildPolarisProfileRoute.entrypoint")(r("JSResourceForInteraction")("PolarisProfileTaggedTabRoot.react").__setRef("PolarisProfileTaggedTabRoot.entrypoint"),function(e){var t=e.routeProps;return{queries:{contentQuery:{environmentProviderOptions:{preloaderGroup:"ig_web_profile_feed"},options:{},parameters:r("PolarisProfileTaggedTabContentQuery$Parameters"),variables:{count:12,user_id:t.id}}}}});l.default=e}),98);
__d("PolarisStoriesHighlightsRoot.entrypoint",["JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){return{queries:{}}},root:r("JSResourceForInteraction")("PolarisStoriesHighlightsRoot.react").__setRef("PolarisStoriesHighlightsRoot.entrypoint")};l.default=e}),98);